import type { Application, User } from './types';

export const users: User[] = [
  { id: 'user-1', firstName: 'Alex', lastName: 'Doe', email: 'alex.doe@example.com', avatarUrl: 'https://placehold.co/40x40.png' },
  { id: 'user-2', firstName: 'Jane', lastName: 'Smith', email: 'jane.smith@example.com', avatarUrl: 'https://placehold.co/40x40.png' },
  { id: 'user-3', firstName: 'U', lastName: 'Ser', email: 'u.ser@example.com', avatarUrl: 'https://placehold.co/40x40.png' },
];

export const applications: Omit<Application, 'user'>[] = [
  {
    id: 'app-elastic',
    companyName: 'Elastic',
    jobTitle: 'Software Engineer',
    jobUrl: 'https://example.com/job/elastic',
    category: 'SRE/Devops',
    status: 'Yet to Apply',
    userId: 'user-3',
  },
  {
    id: 'app-1',
    companyName: 'Innovate Inc.',
    jobTitle: 'Senior Frontend Engineer',
    jobUrl: 'https://example.com/job/1',
    category: 'SWE',
    status: 'Applied',
    userId: 'user-1',
    notes: 'Reached out to John Smith on LinkedIn. He is a manager in the frontend team.',
    appliedOn: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
  },
  {
    id: 'app-2',
    companyName: 'DataDriven Co.',
    jobTitle: 'Data Scientist',
    jobUrl: 'https://example.com/job/2',
    category: 'Data Scientist',
    status: 'Interview',
    userId: 'user-1',
    notes: 'Interview scheduled for next Tuesday. Be prepared to discuss the case study.',
    appliedOn: new Date(new Date().setDate(new Date().getDate() - 7)).toISOString(),
    dueDate: new Date(new Date().setDate(new Date().getDate() + 3)).toISOString(),
  },
  {
    id: 'app-3',
    companyName: 'SecureCloud Ltd.',
    jobTitle: 'DevOps Engineer',
    jobUrl: 'https://example.com/job/3',
    category: 'SRE/Devops',
    status: 'OA',
    userId: 'user-2',
    appliedOn: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
    dueDate: new Date(new Date().setDate(new Date().getDate() + 7)).toISOString(),
  },
  {
    id: 'app-4',
    companyName: 'QuantumLeap',
    jobTitle: 'Quantitative Analyst',
    jobUrl: 'https://example.com/job/4',
    category: 'Quant',
    status: 'Offer',
    userId: 'user-1',
    appliedOn: new Date(new Date().setDate(new Date().getDate() - 14)).toISOString(),
  },
  {
    id: 'app-5',
    companyName: 'SysCore',
    jobTitle: 'Systems Engineer',
    jobUrl: 'https://example.com/job/5',
    category: 'Systems',
    status: 'Interview',
    userId: 'user-2',
    appliedOn: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString(),
    dueDate: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString(),
  },
    {
    id: 'app-6',
    companyName: 'Innovate Inc.',
    jobTitle: 'Junior SWE',
    jobUrl: 'https://example.com/job/6',
    category: 'SWE',
    status: 'Interview',
    userId: 'user-2',
    appliedOn: new Date().toISOString(),
  },
  {
    id: 'app-7',
    companyName: 'NextGen AI',
    jobTitle: 'Machine Learning Engineer',
    jobUrl: 'https://example.com/job/7',
    category: 'Data Scientist',
    status: 'Applied',
    userId: 'user-2',
    appliedOn: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
  },
];
